# Generated by Django 3.2.5 on 2021-08-12 14:08

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('home_address', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=50)),
                ('age', models.DateField()),
                ('education_qualification', models.CharField(max_length=150)),
                ('shop_location', models.CharField(max_length=150)),
                ('internet_usage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('skill', models.CharField(max_length=500)),
                ('working_duration', models.CharField(max_length=50)),
                ('working_mode', models.CharField(choices=[('Alone', 'ALONE'), ('Team', 'TEAM')], max_length=150)),
                ('deadline_handling', models.TextField(max_length=500)),
                ('project', models.TextField(max_length=500)),
                ('home_service', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('expectation', models.TextField(max_length=500)),
                ('relevant_information', models.TextField(max_length=500)),
                ('passport', models.ImageField(upload_to=registration.models.image_location)),
                ('work_evidence', models.FileField(upload_to=registration.models.file_location)),
            ],
        ),
    ]
