# Generated by Django 3.2.5 on 2021-08-12 16:27

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='passport',
            field=models.ImageField(blank=True, upload_to=registration.models.image_location),
        ),
        migrations.AlterField(
            model_name='professional',
            name='work_evidence',
            field=models.FileField(blank=True, upload_to=registration.models.file_location),
        ),
    ]
