# Generated by Django 3.2.6 on 2021-08-13 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210812_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='full_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='home_address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='age',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='professional',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='other_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='street',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
