# Generated by Django 3.2.6 on 2021-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210813_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='home_service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='internet_usage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='working_mode',
            field=models.CharField(max_length=150),
        ),
    ]
