# Generated by Django 3.2.6 on 2021-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210813_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='phone',
            field=models.IntegerField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
