# Generated by Django 3.2.6 on 2021-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210813_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='choice',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
