# Generated by Django 3.2.6 on 2021-08-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_professional_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='choice',
        ),
    ]
