# Generated by Django 3.2.6 on 2021-08-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_professional_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='other_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
