# Generated by Django 3.2.6 on 2021-08-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_professional_other_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
